### ISSUE TITLE
Unclear instructions about output file in annotate-vcf

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Squirls#37]
This command
```
annotate-vcf squirls-config.yml refseq_109_hg38.ser example38.vcf  /Users/abc/Desktop/ 
```

produces the following file
```
Writing HTML output to `/Users/abc/Desktop/.html`
```

The instructions say ``path/to/output`` but do not specify if a filename or a directory is required.

However, providing a full file name leads to writing ``name.html.html``

I think the required output is "path to directory plus prefix" but it would be clearer to have --outdir and --prefix or simply --outname (without adding an HTML suffix unless there is not file suffix)

**Comment by ielis** [comment]
Hi @pnrobinson thanks for pointing out the issue that happens when the user provides path to a folder instead of to a file prefix. I added additional instructions into the RTD regarding what exactly the `output` positional argument accepts.

I also added special handling of a situation when the user provides `/Users/abc/Desktop` and `Desktop` is an existing folder. In this case the results will be stored at `/Users/abc/Desktop/squirls*`.

I do not like adding two or three CLI arguments just to specify output, I think one argument is enough.
