### ISSUE TITLE
Slow speeds for larger files

### ISSUE THREAD

**Issue by kvn95ss** [TheJacksonLaboratory/Squirls#46]
Hello,

I have a vcf file with ~2 million alleles (SNPs and indels). When using Squirls (Under self-made docker image), the vcf loads and performs at rate of ~500 variants per second.
```
07:08:29.715 [main] INFO  o.m.s.c.c.a.AnnotateVcfCommand - Reading variants from `/home/input/squirls.vcf`
07:08:35.954 [splice-worker-14] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 5,000 alleles at 801.54 items/s
07:08:46.559 [splice-worker-18] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 10,000 alleles at 471.43 items/s
07:08:57.669 [splice-worker-28] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 15,000 alleles at 450.09 items/s
07:09:08.532 [splice-worker-15] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 20,000 alleles at 460.32 items/s
07:09:18.408 [splice-worker-10] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 25,000 alleles at 506.28 items/s
07:09:27.828 [splice-worker-20] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 30,000 alleles at 530.84 items/s
```

But towards the tail end of file, the speed drops down quite drastically

```
08:13:34.097 [splice-worker-25] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,710,000 alleles at 118.75 items/s
08:14:42.166 [splice-worker-5] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,715,000 alleles at 73.46 items/s
08:57:30.943 [splice-worker-8] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,720,000 alleles at 1.95 items/s
09:18:01.263 [splice-worker-1] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,725,000 alleles at 4.06 items/s
09:25:52.890 [splice-worker-24] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,730,000 alleles at 10.6 items/s
10:20:48.481 [splice-worker-22] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,735,000 alleles at 1.52 items/s
10:34:00.314 [splice-worker-29] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,740,000 alleles at 6.31 items/s
```

It is still using close to 30 threads. What could be the reason for such slow down?

FYI, the system has 56 threads, 378 GB RAM and ~ 2 TB free HDD (on raid 5).

**Comment by ielis** [comment]
Hello @kvn95ss , on the first glance, the issue may be caused by 2 things:
- The number of variants is not small, and SQUIRLS keeps all variants in memory during the annotation. This can fill the JVM heap, trigger many GC events, and make the app super slow. Did you start the JVM with enough memory (the `-Xmx` option)?
- The allele annotation is parallelized, but the variant corpus is split into `n` chunks with the equal size, one per thread. The chunks are analyzed in parallel, but some threads may finish before the others. If this is the case, we would  see similar messages in the log:
  ```
  09:25:52.890 [splice-worker-24] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,730,000 alleles at 10.6 items/s
  10:20:48.481 [splice-worker-24] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,735,000 alleles at 1.52 items/s
  10:34:00.314 [splice-worker-24] INFO  o.m.squirls.cli.cmd.ProgressReporter - Processed 1,740,000 alleles at 6.31 items/s
  ```
  note the same thread name in the log. However, we see different threads in your log output, so I am not sure this is the case. Also, there is nothing we can do about this in the short term.

Can you verify you're providing JVM with enough memory and check back?

**Comment by kvn95ss** [comment]
Hay, 

When running the program I haven't restricted the memory with ```-Xmx```. However, I got the default maxheapsize with this command ```java -XX:+PrintFlagsFinal -version | grep HeapSize``` and it is around 32 GB. I shall increase it to 100 GB and see if that helps.

**Comment by kvn95ss** [comment]
Just an update, i used 100gb memory using ```-Xmx``` and was able to generate scores within an hour.
